language: ruby
rvm:
  - 2.7.0
  - 3.0.0
  - 3.1.0
  - 3.2.0

env:
  - RAILS_VERSION='~> 5.2'
  - RAILS_VERSION='~> 6.0'
  - RAILS_VERSION='~> 6.0' FARADAY_VERSION='< 1.0'
install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"
